# SPDX-FileCopyrightText: SUSE LLC
# SPDX-License-Identifier: Apache-2.0

---
name: Backport PR

# Backport the changes made in an origin PR to the `release` branch of
# a repository by creating new backport PR. The backported commit is
# signed.
#
# We're reacting on two triggers for executing a backport:
# 1. Merge a PR that has a label `backport`.
# 2. Label an already merged PR with `backport` label.
#
# System of two labels is used to prevent accidental duplicate
# backport -- 'backport' is the command label, while
# `released-as-hotfix` is the protection label.

on:
  pull_request:
    branches: [main]
    types: [closed, labeled]

jobs:
  backport:
    name: Backport
    uses: ./.github/workflows/backport-pr.yaml
    secrets:
      gh_token: ${{ secrets.TRENTOBOT_GH_PAT }}
      ssh_key: ${{ secrets.TRENTOBOT_SSH_KEY }}
      gpg_key: ${{ secrets.TRENTOBOT_GPG_KEY }}
